services:
    api_platform.http_cache.purger:
        class: Darkweak\SouinApiPlatformBundle\HttpCache\SouinRegexPurger
        arguments:
            $clients: ['@http_client']
            $souinBaseHost: '%souin_api_platform.base.host%'
            $souinBaseUrl: '%souin_api_platform.base.url%'
            $souinBaseApiPath: '%souin_api_platform.base.api_path%'
            $souinApiSouinPath: '%souin_api_platform.api.souin.path%'
            $souinApiAuthenticationPath: '%souin_api_platform.api.authentication.path%'
            $username: '%souin_api_platform.api.authentication.username%'
            $password: '%souin_api_platform.api.authentication.password%'
            $logger: '@logger'
