services:
    api_platform.http_cache.purger:
        class: Darkweak\SouinApiPlatformBundle\HttpCache\SouinRegexPurger
        arguments:
            $clients: ['@http_client']
            $souinBaseHost: '%souin_api_platform.base.host%'
            $souinBaseApiPath: '%souin_api_platform.base.api_path%'
            $souinApiSouinPath: '%souin_api_platform.api.souin.path%'
            $souinApiAuthenticationPath: '%souin_api_platform.api.authentication.path%'
            $username: '%souin_api_platform.api.authentication.username%'
            $password: '%souin_api_platform.api.authentication.password%'
            $logger: '@logger'

    api_platform.http_cache.listener.response.add_tags:
        class: Darkweak\SouinApiPlatformBundle\HttpCache\EventListener\SouinAddTagsListener
        arguments:
            $iriConverter: '@api_platform.iri_converter'
        tags:
            - { name: 'kernel.event_listener', event: kernel.response, method: onKernelResponse, priority: -2 }
